immutable_var=1,'apple',True
print(immutable_var)
print(immutable_var[0])
immutable_var[0]=2
print(immutable_var)
mutable_list=[1,'apple',True]
print(mutable_list)
mutable_list[0]=2
print(mutable_list)
