my_dict={'Alex':1970,'Betty':1980,'Charles':1990}
print(my_dict)
print(my_dict['Alex'])
print(my_dict.get('Dan'))
my_dict.update({'Dan':2000,'Eve':2010})
print(my_dict)
my_dict.pop('Eve')
print(my_dict)
my_set={'auto','car','bus',1,2,3,2,3,'bus','auto',(5,6),'море'}
print(my_set)
my_set.add('boat')
my_set.add(7)
my_set.remove(1)
print(my_set)
